name: Exemplo Output
run-name: Exemplo workflow para output, executado por ${{ github.actor }}

on: 
    workflow_dispatch
jobs:
  gerando_output:
      runs-on: ubuntu-latest
      steps:
          - name: Gerando output usando shell
            id: exemplo-output
            run: |
              ACTION_RANDOM=$(( $RANDOM ))
              echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT

          - name: Exibindo o output da action exemplo output
            run: echo "${{ steps.exemplo-output.outputs.action_random}}"

          - name: Gerando output usando Action gerador de senha 
            id: generated-password
            uses: aammiramirza/RandomPasswordGenerator@v1.1
            with:
              length: 15

          - name: Exibindo o output da action de password
            run: echo "${{ steps.generated-password.outputs.password }}"
